### ISSUE TITLE
versio 1.5.0

### ISSUE THREAD

**Issue by veepee78** [Razer2015/NordeaTunnusluvut_Patched#1]
Löytyisikö vastaavia ohjeita 1.5.0 versiota varten? Nähtävästi tiedostonimet eivät enää täsmää, tein ohjeen muutokset ainoaan 19k tiedostoon, mutta roottitarkastus ei sillä poistunut..

Lisäksi purku ja pakkaus piti tehdä linuxin puolella, windows ei tykännyt tiedostonimistä.

edit: niin ja kiitos toki mainiosta ohjeesta!

**Comment by Razer2015** [comment]
Juuh, ne on vaihtanut tota root checkkiä aika lailla eli vanha tapa ei enää toimi. Päivitän tohon uuden ohjeen, menee pieni hetki...

**Comment by Razer2015** [comment]
@veepee78 Eli tossa ohjeet mitkä toimii 1.5.0 versioon: https://github.com/Razer2015/NordeaTunnusluvut_Patched/wiki/Tunnusluvut-1.5.0-Patch-Instructions

**Comment by veepee78** [comment]
Wau, olipa nopeeta! Testaan jussin jälkeen..

**Comment by veepee78** [comment]
hyvin toimii!
