### ISSUE TITLE
Näyttäisi 1.5.1 versio tulleen jakoon

### ISSUE THREAD

**Issue by Timbets** [Razer2015/NordeaTunnusluvut_Patched#2]

**Comment by Razer2015** [comment]
Juuh, en kerkee ihan vielä päivittään ohjetta mutta samalla tavalla patchataan kun 1.5.0. On vaan hiukan eri polussa. Eli, jos luonnistuu muokkaaminen ni alla olevista funktioista korvaat. Katotaan, jos myöhemmin tänään saan päivitettyä.

1.5.0:
util.m.e -> d
util.m.e -> d

1.5.1:
util.m.d -> b
util.m.d -> c
